"""add_jd_and_match_tables

Revision ID: b8efdbbc07e9
Revises: a6589792bf54
Create Date: 2026-06-03 17:33:54.097394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8efdbbc07e9'
down_revision: Union[str, None] = 'a6589792bf54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('google_auth_codes_code_key'), 'google_auth_codes', type_='unique')
    op.drop_index(op.f('ix_google_auth_codes_user_id'), table_name='google_auth_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_google_auth_codes_user_id'), 'google_auth_codes', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('google_auth_codes_code_key'), 'google_auth_codes', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
