"""add_job_application_tracker_models

Revision ID: 6fae603af145
Revises: 4dcda0537a5a
Create Date: 2026-06-04 10:14:12.356149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fae603af145'
down_revision: Union[str, None] = '4dcda0537a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE application_status ADD VALUE IF NOT EXISTS 'ASSESSMENT'")
    op.execute("ALTER TYPE application_status ADD VALUE IF NOT EXISTS 'WITHDRAWN'")
    op.create_table('application_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_status_history_application_id'), 'application_status_history', ['application_id'], unique=False)
    op.add_column('job_applications', sa.Column('resume_id', sa.UUID(), nullable=True))
    op.add_column('job_applications', sa.Column('job_id', sa.UUID(), nullable=True))
    op.add_column('job_applications', sa.Column('company_name', sa.String(length=255), nullable=False))
    op.add_column('job_applications', sa.Column('job_url', sa.String(length=1024), nullable=True))
    op.execute("CREATE TYPE application_priority AS ENUM ('LOW', 'MEDIUM', 'HIGH')")
    op.add_column('job_applications', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='application_priority'), nullable=False))
    op.add_column('job_applications', sa.Column('next_interview_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('job_applications', 'source',
               existing_type=postgresql.ENUM('LINKEDIN', 'NAUKRI', 'INDEED', 'COMPANY_WEBSITE', 'REFERRAL', 'OTHER', name='application_source'),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('job_applications', 'application_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_foreign_key(None, 'job_applications', 'job_descriptions', ['job_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'job_applications', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    op.drop_column('job_applications', 'company')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.alter_column('job_applications', 'application_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('job_applications', 'source',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('LINKEDIN', 'NAUKRI', 'INDEED', 'COMPANY_WEBSITE', 'REFERRAL', 'OTHER', name='application_source'),
               nullable=False)
    op.drop_column('job_applications', 'next_interview_date')
    op.drop_column('job_applications', 'priority')
    op.drop_column('job_applications', 'job_url')
    op.drop_column('job_applications', 'company_name')
    op.drop_column('job_applications', 'job_id')
    op.drop_column('job_applications', 'resume_id')
    op.drop_index(op.f('ix_application_status_history_application_id'), table_name='application_status_history')
    op.drop_table('application_status_history')
    # ### end Alembic commands ###
