"""add_optimization_models

Revision ID: 4dcda0537a5a
Revises: 12b517928551
Create Date: 2026-06-03 19:03:24.730503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dcda0537a5a'
down_revision: Union[str, None] = '12b517928551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('job_description_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_job_description_id'), 'optimization_runs', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_optimization_runs_resume_id'), 'optimization_runs', ['resume_id'], unique=False)
    op.create_index('ix_optimization_runs_resume_job', 'optimization_runs', ['resume_id', 'job_description_id'], unique=False)
    op.create_table('resume_optimizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('optimization_type', sa.Enum('KEYWORD', 'BULLET_REWRITE', 'SKILL_ADDITION', 'SUMMARY_IMPROVEMENT', 'ATS_FIX', name='optimizationtype'), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('suggested_text', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='optimizationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_optimizations_run_id'), 'resume_optimizations', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_optimizations_run_id'), table_name='resume_optimizations')
    op.drop_table('resume_optimizations')
    op.drop_index('ix_optimization_runs_resume_job', table_name='optimization_runs')
    op.drop_index(op.f('ix_optimization_runs_resume_id'), table_name='optimization_runs')
    op.drop_index(op.f('ix_optimization_runs_job_description_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    # ### end Alembic commands ###
