"""add_matched_skills_to_resume_matches

Revision ID: 12b517928551
Revises: b8efdbbc07e9
Create Date: 2026-06-03 17:43:10.282417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12b517928551'
down_revision: Union[str, None] = 'b8efdbbc07e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_matches', sa.Column('matched_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_matches', 'matched_skills')
    # ### end Alembic commands ###
